- hosts: cluster
  vars:
    OS: "Debian_11"
    CRIO_VERSION: "1.24"
  roles:
  - setup_env
  - container_runtime
  - k8s_installation

- hosts: masters[0]
  roles:
  - setup_cluster

- hosts: masters[1:]
  roles:
  - master_join_cluster

- hosts: workers
  roles:
  - worker_join_cluster
