- name: Get join command
  command: kubeadm token create --print-join-command
  register: kubeadm_join_cmd
  delegate_to: "{{ groups['masters'][0] }}"

- name: Set fact
  set_fact:
    join_cmd: "{{ kubeadm_join_cmd.stdout }}" 

- name: Worker join cluster
  command: "{{ join_cmd }}"
