- name: disable swap mount
  raw: sed -i "s/UUID=.*swap.*//g" /etc/fstab

- name: disable swap space
  raw: swapoff -a

- name: install essential packages
  apt:
    pkg:
     - curl
     - gpg
    state: latest
    update_cache: true

- name: enable br_netfilter
  raw: echo "br_netfilter" > /etc/modules-load.d/k8s.conf

- name: enable IPv4 forwarding
  raw: sed -i "s/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/g" /etc/sysctl.conf

- name: copy sysctl config
  copy:
    src: sysctl-k8s.conf
    dest: /etc/sysctl.d/k8s.conf

- name: apply br_netfilter
  raw: modprobe br_netfilter

- name: apply networking config
  raw: sysctl -a && sysctl --system
