- name: create certificates folder
  file:
    path: /etc/kubernetes/pki/etcd
    state: directory
    recurse: yes

- name: Fetch kubernetes master pki files from primary master
  copy:
    src: /tmp/kubeadm-ha/pki/{{ item }}
    dest: /etc/kubernetes/pki/{{ item }}
  with_items:
    - ca.crt
    - ca.key
    - sa.key
    - sa.pub
    - front-proxy-ca.crt
    - front-proxy-ca.key

- name: Fetch kubernetes master etcd files from primary master
  copy:
    src: /tmp/kubeadm-ha/pki/etcd/{{ item }}
    dest: /etc/kubernetes/pki/etcd/{{ item }}
  with_items:
    - ca.crt
    - ca.key

- name: Fetching kubernetes master admin files from primary master
  copy:
    src: /tmp/kubeadm-ha/{{ item }}
    dest: /etc/kubernetes/{{ item }}
  with_items:
    - admin.conf

- name: Get join command
  command: kubeadm token create --print-join-command
  register: kubeadm_join_cmd
  delegate_to: "{{ groups['masters'][0] }}"

- name: Set fact
  set_fact:
      join_cmd: "{{ kubeadm_join_cmd.stdout }}" 

- name: Master join cluster
  command: "{{ join_cmd }} --control-plane"
